name: Node.js CI

# Trigger the workflow on push to any branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to be run
jobs:
  # Define the job named 'build'
  build:
    runs-on: ubuntu-latest # The environment to run the job in
    
    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js with a specific version
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version (use the version that matches your project)

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Run linting (Optional - if you're using a linter like ESLint)
    - name: Run ESLint
      run: npm run lint

    # Step 5: Run tests
    - name: Run tests
      run: npm test
